### ISSUE TITLE
AssertionError：data/amass/amass_30fps_legacy_db.pt

### ISSUE THREAD

**Issue by ywdong** [GuyTevet/MotionCLIP#13]
Hi，thx for your geat job!!
I want to use the code to run text_to_motion scrpit, just like: 

`python -m src.visualize.text2motion ./exps/paper-model/checkpoint_0100.pth.tar --input_file assets/paper_texts.txt`

But I got the below exception:

`Traceback (most recent call last):
  File "/data/miniconda3/envs/motion_clip/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/envs/motion_clip/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/group/20000/weidongyang/pose-estimation/motion_clip/MotionCLIP/src/visualize/text2motion.py", line 41, in <module>
    main()
  File "/group/20000/weidongyang/pose-estimation/motion_clip/MotionCLIP/src/visualize/text2motion.py", line 21, in main
    model, datasets = get_model_and_data(parameters, split='vald')
  File "/group/20000/weidongyang/pose-estimation/motion_clip/MotionCLIP/src/utils/get_model_and_data.py", line 26, in get_model_and_data
    datasets = get_datasets(parameters, clip_preprocess, split)
  File "/group/20000/weidongyang/pose-estimation/motion_clip/MotionCLIP/src/datasets/get_dataset.py", line 18, in get_datasets
    dataset = DATA(split=split, clip_preprocess=clip_preprocess, **parameters)
  File "/group/20000/weidongyang/pose-estimation/motion_clip/MotionCLIP/src/datasets/amass.py", line 142, in __init__
    assert os.path.exists(self.datapath)
AssertionError`

Where can I to get tht pt file？ Much appreciate！

**Comment by ywdong** [comment]
I have forgot to generate the data.

**Comment by dsdf783** [comment]
I don't know how to get the file 'amass_30fps_legacy_db.pt', how do you generate it?
