### ISSUE TITLE
AttributeError: 'AMASS' object has no attribute 'nfeats'

### ISSUE THREAD

**Issue by DTOSCANO461** [GuyTevet/MotionCLIP#36]
when running "python -m src.visualize.text2motion ./exps/paper-model/checkpoint_0100.pth.tar --input_file assets/paper_texts.txt" i get a that error. i just change.

The problem is in src/datasets/dataset.py", line 371.

I can run the script by assigning values to those variables in lines 371 and 372, so it seems that the issue lies in the parameter passing.

Thanks for your time, im  kind of a noob :)

**Comment by GuyTevet** [comment]
Hi @DTOSCANO461 ,
I wasn't able to reproduce your bug, did you change something in the code? Can you share the full error traceback?

**Comment by DTOSCANO461** [comment]
i did make some changes. and probably... it could be the cause. But the first error i got was this:


python -m src.datasets.amass_parser --dataset_name amass
Loading babel labels
DONE! - Loading babel labels
Loading Body Models
DONE! - Loading Body Models
Reading Transitions_mocap sequence...
  0%|                                                                                                                           | 0/111 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mulinux/anaconda3/envs/motionclip/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mulinux/anaconda3/envs/motionclip/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mulinux/Documents/motion/MotionCLIP/src/datasets/amass_parser.py", line 307, in <module>
    db = read_data(args.input_dir,
  File "/home/mulinux/Documents/motion/MotionCLIP/src/datasets/amass_parser.py", line 115, in read_data
    results_dict = read_single_sequence(split_name, dataset_name, seq_folder, seq_name, body_models, target_fps,
  File "/home/mulinux/Documents/motion/MotionCLIP/src/datasets/amass_parser.py", line 138, in read_single_sequence
    actions = [x for x in os.listdir(osp.join(folder, subject)) if x.endswith('.npz')]
NotADirectoryError: [Errno 20] Not a directory: './data/amass/Transitions_mocap/turntwist_kick_poses.npz'

i believe this error is about the '.npz', it is a file, not  a directory. i replaced 'os.listdir(' whith 'list('.

i also include a description of my folder structure in case you need it, probably the structure of Amass DB is wrong. the document is called 'summary_tree_for_Guytevet.txt]'
[summary_tree_for_Guytevet.txt](https://github.com/GuyTevet/MotionCLIP/files/13628801/summary_tree_for_Guytevet.txt)
